# Generated by Django 2.2.5 on 2019-09-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('exercise', models.CharField(max_length=50)),
                ('programme', models.CharField(max_length=50)),
            ],
        ),
    ]
