# Generated by Django 2.2.5 on 2019-09-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_auto_20190905_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='items', to='gymapp.Category'),
        ),
    ]
