# Generated by Django 2.2.5 on 2019-09-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_item_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
    ]
