# Generated by Django 2.2.5 on 2019-09-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_remove_item_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='gymapp.Category'),
        ),
    ]
