# Generated by Django 2.2.5 on 2019-09-04 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_auto_20190904_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='name',
            new_name='firstname',
        ),
    ]
