# Generated by Django 2.2.5 on 2019-09-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_auto_20190905_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('weigth', models.IntegerField()),
                ('items', models.ManyToManyField(blank=True, related_name='personalbest', to='gymapp.Item')),
            ],
        ),
    ]
