# Generated by Django 2.2.5 on 2019-09-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_auto_20190906_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalbest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='personalbest',
        ),
        migrations.AddField(
            model_name='item',
            name='personalbests',
            field=models.ManyToManyField(blank=True, related_name='items', to='gymapp.Personalbest'),
        ),
    ]
