# Generated by Django 2.2.5 on 2019-09-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_auto_20190906_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='image',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
