# Generated by Django 2.2.5 on 2019-09-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_programme_image'),
        ('gymapp', '0009_auto_20190910_1610'),
    ]

    operations = [
    ]
