# Generated by Django 2.2.5 on 2019-09-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_auto_20190910_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbest',
            name='weight',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalbest',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
