# Generated by Django 2.2.5 on 2019-09-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_auto_20190910_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='personalbests',
        ),
        migrations.AddField(
            model_name='personalbest',
            name='item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='personalbests', to='gymapp.Item'),
            preserve_default=False,
        ),
    ]
