# Generated by Django 2.2.5 on 2019-09-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0012_merge_20190911_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
