# Generated by Django 2.2.5 on 2019-09-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0013_programme_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
